"""Theming: colour palettes and the stylesheet built from them.

A theme is a flat set of named colours. Everything visual derives from those
names, so a new theme is a dozen colour values and needs no stylesheet work.
Themes are plain data and round-trip through JSON, which is what lets users
share them and lets GameLab pick up colours generated by Matugen or any other
palette tool.

The default is tuned for OLED panels: true black rather than dark grey, because
black pixels are genuinely off and the difference is visible.
"""

from __future__ import annotations

import json

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

# Corner radius, spacing and sizing live here rather than being sprinkled
# through the stylesheet, so the whole interface can be tightened or loosened
# from one place.
RADIUS_LARGE = 18
RADIUS = 12
RADIUS_SMALL = 8
SPACING = 12

# Cover art is 2:3, the standard portrait box-art ratio Steam and every
# thumbnail archive use.
COVER_RATIO = 3 / 2
COVER_WIDTHS = {"small": 120, "medium": 160, "large": 200, "huge": 260}


@dataclass
class Theme:
    """A named colour palette."""

    name: str = "Rose Dark"
    background: str = "#000000"
    surface: str = "#0d0d10"
    panel: str = "#14141a"
    elevated: str = "#1c1c24"
    accent: str = "#e0607e"
    accent_muted: str = "#8c3d4f"
    text: str = "#e8e6ea"
    text_dim: str = "#8a8791"
    border: str = "#22222c"
    success: str = "#7fc98a"
    warning: str = "#e0b060"
    error: str = "#e06c75"
    #: Drawn behind cover art while it loads, and for games with no art.
    placeholder: str = "#1a1a22"

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Theme":
        """Build a theme from a dict, ignoring unknown keys.

        Unknown keys are dropped rather than raising, so a theme file written
        by a newer version still loads in an older one.
        """
        fields = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in data.items() if k in fields})

    @classmethod
    def load(cls, path: Path) -> "Theme":
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))

    def save(self, path: Path) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")


# ── Built-in themes ───────────────────────────────────────────────

THEMES: dict[str, Theme] = {
    "rose-dark": Theme(),
    "rose-oled": Theme(
        name="Rose OLED",
        background="#000000", surface="#000000", panel="#0a0a0d",
        elevated="#141419", accent="#e0607e", accent_muted="#7a3546",
        text="#f0eef2", text_dim="#7c7986", border="#1a1a20",
        placeholder="#101014",
    ),
    "tokyo-night": Theme(
        name="Tokyo Night",
        background="#1a1b26", surface="#16161e", panel="#1e2030",
        elevated="#292e42", accent="#7aa2f7", accent_muted="#3d5a8c",
        text="#c0caf5", text_dim="#565a78", border="#292e42",
        success="#9ece6a", warning="#e0af68", error="#f7768e",
        placeholder="#222436",
    ),
    "catppuccin-mocha": Theme(
        name="Catppuccin Mocha",
        background="#1e1e2e", surface="#181825", panel="#313244",
        elevated="#45475a", accent="#cba6f7", accent_muted="#6c5b8a",
        text="#cdd6f4", text_dim="#6c7086", border="#45475a",
        success="#a6e3a1", warning="#f9e2af", error="#f38ba8",
        placeholder="#302d41",
    ),
    "gruvbox": Theme(
        name="Gruvbox Dark",
        background="#1d2021", surface="#282828", panel="#32302f",
        elevated="#3c3836", accent="#fabd2f", accent_muted="#8f7218",
        text="#ebdbb2", text_dim="#928374", border="#3c3836",
        success="#b8bb26", warning="#fe8019", error="#fb4934",
        placeholder="#32302f",
    ),
    "nord": Theme(
        name="Nord",
        background="#2e3440", surface="#3b4252", panel="#434c5e",
        elevated="#4c566a", accent="#88c0d0", accent_muted="#4d707a",
        text="#eceff4", text_dim="#7b88a1", border="#4c566a",
        success="#a3be8c", warning="#ebcb8b", error="#bf616a",
        placeholder="#3b4252",
    ),
    "rose-pine": Theme(
        name="Rosé Pine",
        background="#191724", surface="#1f1d2e", panel="#26233a",
        elevated="#312f44", accent="#ebbcba", accent_muted="#8c6f6e",
        text="#e0def4", text_dim="#6e6a86", border="#26233a",
        success="#9ccfd8", warning="#f6c177", error="#eb6f92",
        placeholder="#232132",
    ),
    "everforest": Theme(
        name="Everforest",
        background="#2b3339", surface="#323c41", panel="#3a454a",
        elevated="#445055", accent="#a7c080", accent_muted="#61754b",
        text="#d3c6aa", text_dim="#859289", border="#445055",
        success="#a7c080", warning="#dbbc7f", error="#e67e80",
        placeholder="#374146",
    ),
    "dracula": Theme(
        name="Dracula",
        background="#282a36", surface="#21222c", panel="#343746",
        elevated="#44475a", accent="#bd93f9", accent_muted="#6b5296",
        text="#f8f8f2", text_dim="#6272a4", border="#44475a",
        success="#50fa7b", warning="#ffb86c", error="#ff5555",
        placeholder="#2f313d",
    ),
    "light": Theme(
        name="Light",
        background="#faf9fb", surface="#ffffff", panel="#f1eff4",
        elevated="#e6e3ea", accent="#b34464", accent_muted="#d99cad",
        text="#1c1a20", text_dim="#6e6a76", border="#dcd8e0",
        success="#3f8a4c", warning="#9a6b1a", error="#b3384a",
        placeholder="#e9e6ee",
    ),
}

DEFAULT_THEME = "rose-dark"


def get_theme(name: str) -> Theme:
    """Look up a built-in theme, falling back to the default."""
    return THEMES.get(name, THEMES[DEFAULT_THEME])


def list_theme_names() -> list[tuple[str, str]]:
    """(id, display name) for every built-in theme."""
    return [(key, theme.name) for key, theme in THEMES.items()]


# ── Stylesheet ────────────────────────────────────────────────────

def stylesheet(theme: Theme) -> str:
    """The Qt stylesheet for a theme.

    Everything rounded, matching the Hyprland configuration this interface is
    modelled on. Scrollbars are slim and unobtrusive; focus rings use the
    accent rather than the platform default so keyboard navigation stays
    visible in Big Picture mode.
    """
    return f"""
    QWidget {{
        background-color: {theme.background};
        color: {theme.text};
        font-size: 14px;
    }}

    QMainWindow, QDialog {{
        background-color: {theme.background};
    }}

    /* ── Panels ─────────────────────────────────────────────── */

    #Sidebar {{
        background-color: {theme.surface};
        border-right: 1px solid {theme.border};
    }}

    #TopBar {{
        background-color: {theme.surface};
        border-bottom: 1px solid {theme.border};
    }}

    #DetailPanel {{
        background-color: {theme.panel};
        border-radius: {RADIUS_LARGE}px;
    }}

    /* ── Buttons ────────────────────────────────────────────── */

    QPushButton {{
        background-color: {theme.panel};
        color: {theme.text};
        border: 1px solid {theme.border};
        border-radius: {RADIUS}px;
        padding: 8px 16px;
    }}

    QPushButton:hover {{
        background-color: {theme.elevated};
        border-color: {theme.accent_muted};
    }}

    QPushButton:pressed {{
        background-color: {theme.accent_muted};
    }}

    QPushButton:disabled {{
        color: {theme.text_dim};
        background-color: {theme.surface};
    }}

    QPushButton#Primary {{
        background-color: {theme.accent};
        color: {theme.background};
        border: none;
        font-weight: 600;
    }}

    QPushButton#Primary:hover {{
        background-color: {theme.text};
    }}

    /* Sidebar entries read as list rows, not buttons. */
    QPushButton#SidebarItem {{
        background-color: transparent;
        border: none;
        border-radius: {RADIUS}px;
        padding: 9px 12px;
        text-align: left;
    }}

    QPushButton#SidebarItem:hover {{
        background-color: {theme.panel};
    }}

    QPushButton#SidebarItem:checked {{
        background-color: {theme.accent_muted};
        color: {theme.text};
        font-weight: 600;
    }}

    /* ── Inputs ─────────────────────────────────────────────── */

    QLineEdit {{
        background-color: {theme.panel};
        border: 1px solid {theme.border};
        border-radius: {RADIUS}px;
        padding: 8px 14px;
        selection-background-color: {theme.accent_muted};
    }}

    QLineEdit:focus {{
        border-color: {theme.accent};
    }}

    QComboBox {{
        background-color: {theme.panel};
        border: 1px solid {theme.border};
        border-radius: {RADIUS}px;
        padding: 7px 12px;
    }}

    QComboBox:hover {{
        border-color: {theme.accent_muted};
    }}

    QComboBox::drop-down {{
        border: none;
        width: 24px;
    }}

    QComboBox QAbstractItemView {{
        background-color: {theme.panel};
        border: 1px solid {theme.border};
        border-radius: {RADIUS_SMALL}px;
        selection-background-color: {theme.accent_muted};
        outline: none;
    }}

    QCheckBox::indicator {{
        width: 18px;
        height: 18px;
        border-radius: {RADIUS_SMALL}px;
        border: 1px solid {theme.border};
        background-color: {theme.panel};
    }}

    QCheckBox::indicator:checked {{
        background-color: {theme.accent};
        border-color: {theme.accent};
    }}

    /* ── Scrolling ──────────────────────────────────────────── */

    QScrollArea {{
        border: none;
        background-color: transparent;
    }}

    QScrollBar:vertical {{
        background: transparent;
        width: 10px;
        margin: 0;
    }}

    QScrollBar::handle:vertical {{
        background: {theme.elevated};
        border-radius: 5px;
        min-height: 40px;
    }}

    QScrollBar::handle:vertical:hover {{
        background: {theme.accent_muted};
    }}

    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {{
        height: 0;
        background: none;
    }}

    QScrollBar:horizontal {{
        background: transparent;
        height: 10px;
    }}

    QScrollBar::handle:horizontal {{
        background: {theme.elevated};
        border-radius: 5px;
        min-width: 40px;
    }}

    QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,
    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{
        width: 0;
        background: none;
    }}

    /* ── Misc ───────────────────────────────────────────────── */

    QLabel#Heading {{
        font-size: 24px;
        font-weight: 700;
    }}

    QLabel#Subtle {{
        color: {theme.text_dim};
    }}

    QToolTip {{
        background-color: {theme.elevated};
        color: {theme.text};
        border: 1px solid {theme.border};
        border-radius: {RADIUS_SMALL}px;
        padding: 6px 10px;
    }}

    QMenu {{
        background-color: {theme.panel};
        border: 1px solid {theme.border};
        border-radius: {RADIUS}px;
        padding: 6px;
    }}

    QMenu::item {{
        padding: 7px 22px;
        border-radius: {RADIUS_SMALL}px;
    }}

    QMenu::item:selected {{
        background-color: {theme.accent_muted};
    }}

    QProgressBar {{
        background-color: {theme.panel};
        border: none;
        border-radius: 4px;
        height: 8px;
        text-align: center;
    }}

    QProgressBar::chunk {{
        background-color: {theme.accent};
        border-radius: 4px;
    }}
    """
