"""Theming: colour palettes, interface styles, and the stylesheet built from them.

Appearance is split into two things that vary independently, because users want
them to:

  - a **theme** is a flat set of named colours. Everything coloured derives from
    those names, so a new theme is a dozen values and needs no stylesheet work.
  - a **style** is the shape and weight of the interface: how round the corners
    are, how tightly packed it is, how large the text runs, how heavy the
    borders are.

Keeping them apart is the whole point. Someone who loves Gruvbox but wants sharp
corners, or Rosé Pine at a denser spacing, should not have to choose between
them or hand-edit a stylesheet — any theme composes with any style, and each
axis of a style can be overridden on its own.

Both are plain data and round-trip through JSON, which is what lets users share
them and lets GameLab pick up colours generated by Matugen or any other palette
tool.

The default theme is tuned for OLED panels: true black rather than dark grey,
because black pixels are genuinely off and the difference is visible.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, replace
from pathlib import Path
from typing import Optional

# Cover art is 2:3, the standard portrait box-art ratio Steam and every
# thumbnail archive use.
COVER_RATIO = 3 / 2
COVER_WIDTHS = {"small": 140, "medium": 180, "large": 230, "huge": 290}


@dataclass(frozen=True)
class Style:
    """The shape and weight of the interface, independent of its colours.

    Every field is a plain number so a style can be interpolated, nudged one
    axis at a time, or written out as JSON. `Appearance.style` is what the
    stylesheet reads; nothing here knows or cares which theme it is paired with.
    """

    name: str = "Rounded"

    #: Corner radii. `radius` is the workhorse; the other two are derived from
    #: it by default so a style only has to state one number to feel coherent.
    radius: int = 12
    radius_large: int = 18
    radius_small: int = 8

    #: Gap between panels, and the padding inside them.
    spacing: int = 18
    padding: int = 10

    #: Base font size in points. Everything else scales off it.
    font_size: int = 14
    heading_size: int = 24

    #: Border thickness. 0 gives a flat, borderless look.
    border_width: int = 1

    #: Default cover width key — one of COVER_WIDTHS.
    cover_size: str = "medium"

    #: Whether panels sit on a visibly different background from the window.
    #: Off gives a single-surface look where only spacing separates things.
    elevated_panels: bool = True

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Style":
        """Build a style from a dict, ignoring unknown keys.

        Unknown keys are dropped rather than raising, so a style file written by
        a newer version still loads in an older one.
        """
        fields = set(cls.__dataclass_fields__)
        return cls(**{k: v for k, v in data.items() if k in fields})

    def with_overrides(self, **changes) -> "Style":
        """A copy with individual axes changed — the 'mix and match' primitive.

        Unknown or None values are ignored, so a caller can pass a sparse set of
        user preferences straight through without filtering first.
        """
        fields = set(self.__dataclass_fields__)
        usable = {
            key: value for key, value in changes.items()
            if key in fields and value is not None
        }
        return replace(self, **usable) if usable else self


@dataclass
class Theme:
    """A named colour palette."""

    name: str = "Rose Dark"
    background: str = "#000000"
    surface: str = "#0d0d10"
    panel: str = "#14141a"
    elevated: str = "#1c1c24"
    accent: str = "#e0607e"
    accent_muted: str = "#8c3d4f"
    text: str = "#e8e6ea"
    text_dim: str = "#8a8791"
    border: str = "#22222c"
    success: str = "#7fc98a"
    warning: str = "#e0b060"
    error: str = "#e06c75"
    #: Drawn behind cover art while it loads, and for games with no art.
    placeholder: str = "#1a1a22"

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Theme":
        """Build a theme from a dict, ignoring unknown keys.

        Unknown keys are dropped rather than raising, so a theme file written
        by a newer version still loads in an older one.
        """
        fields = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in data.items() if k in fields})

    @classmethod
    def load(cls, path: Path) -> "Theme":
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))

    def save(self, path: Path) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")


# ── Built-in themes ───────────────────────────────────────────────

THEMES: dict[str, Theme] = {
    "rose-dark": Theme(),
    "rose-oled": Theme(
        name="Rose OLED",
        background="#000000", surface="#000000", panel="#0a0a0d",
        elevated="#141419", accent="#e0607e", accent_muted="#7a3546",
        text="#f0eef2", text_dim="#7c7986", border="#1a1a20",
        placeholder="#101014",
    ),
    "tokyo-night": Theme(
        name="Tokyo Night",
        background="#1a1b26", surface="#16161e", panel="#1e2030",
        elevated="#292e42", accent="#7aa2f7", accent_muted="#3d5a8c",
        text="#c0caf5", text_dim="#565a78", border="#292e42",
        success="#9ece6a", warning="#e0af68", error="#f7768e",
        placeholder="#222436",
    ),
    "catppuccin-mocha": Theme(
        name="Catppuccin Mocha",
        background="#1e1e2e", surface="#181825", panel="#313244",
        elevated="#45475a", accent="#cba6f7", accent_muted="#6c5b8a",
        text="#cdd6f4", text_dim="#6c7086", border="#45475a",
        success="#a6e3a1", warning="#f9e2af", error="#f38ba8",
        placeholder="#302d41",
    ),
    "gruvbox": Theme(
        name="Gruvbox Dark",
        background="#1d2021", surface="#282828", panel="#32302f",
        elevated="#3c3836", accent="#fabd2f", accent_muted="#8f7218",
        text="#ebdbb2", text_dim="#928374", border="#3c3836",
        success="#b8bb26", warning="#fe8019", error="#fb4934",
        placeholder="#32302f",
    ),
    "nord": Theme(
        name="Nord",
        background="#2e3440", surface="#3b4252", panel="#434c5e",
        elevated="#4c566a", accent="#88c0d0", accent_muted="#4d707a",
        text="#eceff4", text_dim="#7b88a1", border="#4c566a",
        success="#a3be8c", warning="#ebcb8b", error="#bf616a",
        placeholder="#3b4252",
    ),
    "rose-pine": Theme(
        name="Rosé Pine",
        background="#191724", surface="#1f1d2e", panel="#26233a",
        elevated="#312f44", accent="#ebbcba", accent_muted="#8c6f6e",
        text="#e0def4", text_dim="#6e6a86", border="#26233a",
        success="#9ccfd8", warning="#f6c177", error="#eb6f92",
        placeholder="#232132",
    ),
    "everforest": Theme(
        name="Everforest",
        background="#2b3339", surface="#323c41", panel="#3a454a",
        elevated="#445055", accent="#a7c080", accent_muted="#61754b",
        text="#d3c6aa", text_dim="#859289", border="#445055",
        success="#a7c080", warning="#dbbc7f", error="#e67e80",
        placeholder="#374146",
    ),
    "dracula": Theme(
        name="Dracula",
        background="#282a36", surface="#21222c", panel="#343746",
        elevated="#44475a", accent="#bd93f9", accent_muted="#6b5296",
        text="#f8f8f2", text_dim="#6272a4", border="#44475a",
        success="#50fa7b", warning="#ffb86c", error="#ff5555",
        placeholder="#2f313d",
    ),
    "light": Theme(
        name="Light",
        background="#faf9fb", surface="#ffffff", panel="#f1eff4",
        elevated="#e6e3ea", accent="#b34464", accent_muted="#d99cad",
        text="#1c1a20", text_dim="#6e6a76", border="#dcd8e0",
        success="#3f8a4c", warning="#9a6b1a", error="#b3384a",
        placeholder="#e9e6ee",
    ),

    # ── Dark ──────────────────────────────────────────────────────
    "catppuccin-macchiato": Theme(
        name="Catppuccin Macchiato",
        background="#24273a", surface="#1e2030", panel="#363a4f",
        elevated="#494d64", accent="#c6a0f6", accent_muted="#6e5a8c",
        text="#cad3f5", text_dim="#6e738d", border="#494d64",
        success="#a6da95", warning="#eed49f", error="#ed8796",
        placeholder="#303446",
    ),
    "kanagawa": Theme(
        name="Kanagawa",
        background="#1f1f28", surface="#16161d", panel="#2a2a37",
        elevated="#363646", accent="#7e9cd8", accent_muted="#4a5b80",
        text="#dcd7ba", text_dim="#727169", border="#363646",
        success="#98bb6c", warning="#ffa066", error="#e82424",
        placeholder="#252530",
    ),
    "nightfox": Theme(
        name="Nightfox",
        background="#192330", surface="#131a24", panel="#212e3f",
        elevated="#29394f", accent="#719cd6", accent_muted="#3d5878",
        text="#cdcecf", text_dim="#71839b", border="#29394f",
        success="#81b29a", warning="#dbc074", error="#c94f6d",
        placeholder="#1d2b3a",
    ),
    "solarized-dark": Theme(
        name="Solarized Dark",
        background="#002b36", surface="#00212b", panel="#073642",
        elevated="#0d4451", accent="#268bd2", accent_muted="#1a5c8a",
        text="#93a1a1", text_dim="#586e75", border="#0d4451",
        success="#859900", warning="#b58900", error="#dc322f",
        placeholder="#063440",
    ),
    "oxocarbon": Theme(
        name="Oxocarbon",
        background="#161616", surface="#0f0f0f", panel="#262626",
        elevated="#393939", accent="#be95ff", accent_muted="#6b52a1",
        text="#f2f4f8", text_dim="#7b7c7e", border="#393939",
        success="#42be65", warning="#ff832b", error="#ee5396",
        placeholder="#1f1f1f",
    ),
    "monokai": Theme(
        name="Monokai",
        background="#272822", surface="#1e1f1c", panel="#333429",
        elevated="#49483e", accent="#a6e22e", accent_muted="#5f7d20",
        text="#f8f8f2", text_dim="#75715e", border="#49483e",
        success="#a6e22e", warning="#e6db74", error="#f92672",
        placeholder="#2e2f28",
    ),
    "synthwave": Theme(
        name="Synthwave",
        background="#241b2f", surface="#1a1425", panel="#2d2140",
        elevated="#3b2d52", accent="#ff7edb", accent_muted="#8c4478",
        text="#f4eee4", text_dim="#8b7fa6", border="#3b2d52",
        success="#72f1b8", warning="#fede5d", error="#fe4450",
        placeholder="#2a1f3a",
    ),
    "matrix": Theme(
        name="Matrix",
        background="#000000", surface="#020a02", panel="#0a160a",
        elevated="#12240f", accent="#00ff6a", accent_muted="#0a7a38",
        text="#c8f7d4", text_dim="#4c8f63", border="#12240f",
        success="#00ff6a", warning="#c8ff00", error="#ff5555",
        placeholder="#081208",
    ),
    "nord-light": Theme(
        name="Nord Light",
        background="#eceff4", surface="#ffffff", panel="#e5e9f0",
        elevated="#d8dee9", accent="#5e81ac", accent_muted="#a3b8d0",
        text="#2e3440", text_dim="#616e88", border="#d8dee9",
        success="#a3be8c", warning="#d08770", error="#bf616a",
        placeholder="#dfe4ec",
    ),

    # ── Light ─────────────────────────────────────────────────────
    "catppuccin-latte": Theme(
        name="Catppuccin Latte",
        background="#eff1f5", surface="#ffffff", panel="#e6e9ef",
        elevated="#dce0e8", accent="#8839ef", accent_muted="#b8a1e0",
        text="#4c4f69", text_dim="#8c8fa1", border="#dce0e8",
        success="#40a02b", warning="#df8e1d", error="#d20f39",
        placeholder="#e2e5ec",
    ),
    "solarized-light": Theme(
        name="Solarized Light",
        background="#fdf6e3", surface="#fffbf0", panel="#eee8d5",
        elevated="#e3ddc8", accent="#268bd2", accent_muted="#9dc4de",
        text="#586e75", text_dim="#93a1a1", border="#e3ddc8",
        success="#859900", warning="#b58900", error="#dc322f",
        placeholder="#efe9d6",
    ),
    "gruvbox-light": Theme(
        name="Gruvbox Light",
        background="#fbf1c7", surface="#f9f5d7", panel="#ebdbb2",
        elevated="#d5c4a1", accent="#b57614", accent_muted="#dfbc8a",
        text="#3c3836", text_dim="#7c6f64", border="#d5c4a1",
        success="#79740e", warning="#af3a03", error="#9d0006",
        placeholder="#eddbb2",
    ),
    "rose-pine-dawn": Theme(
        name="Rosé Pine Dawn",
        background="#faf4ed", surface="#fffaf3", panel="#f2e9e1",
        elevated="#e8ded5", accent="#b4637a", accent_muted="#dcb0bc",
        text="#575279", text_dim="#9893a5", border="#e8ded5",
        success="#286983", warning="#ea9d34", error="#b4637a",
        placeholder="#f4ece4",
    ),

    # ── High contrast ─────────────────────────────────────────────
    # Not a stylistic choice. Everything meets WCAG AA against its own
    # background, for anyone the tuned-down palettes above do not serve.
    "high-contrast": Theme(
        name="High Contrast",
        background="#000000", surface="#000000", panel="#141414",
        elevated="#242424", accent="#ffd400", accent_muted="#8a7300",
        text="#ffffff", text_dim="#d0d0d0", border="#ffffff",
        success="#3dff7a", warning="#ffb000", error="#ff5c5c",
        placeholder="#1a1a1a",
    ),
    "high-contrast-light": Theme(
        name="High Contrast Light",
        background="#ffffff", surface="#ffffff", panel="#f0f0f0",
        elevated="#e0e0e0", accent="#0033cc", accent_muted="#7a92d9",
        text="#000000", text_dim="#333333", border="#000000",
        success="#005c1f", warning="#8a4b00", error="#a80000",
        placeholder="#ebebeb",
    ),
}

DEFAULT_THEME = "rose-dark"


# ── Built-in styles ───────────────────────────────────────────────
#
# Shape, not colour. Each one is a coherent starting point; the settings screen
# lets any axis be overridden on top, so these are presets rather than a menu of
# mutually exclusive choices.

STYLES: dict[str, Style] = {
    "rounded": Style(),
    "sharp": Style(
        name="Sharp",
        radius=0, radius_large=0, radius_small=0,
    ),
    "soft": Style(
        name="Soft",
        radius=18, radius_large=26, radius_small=12,
        spacing=20, padding=12,
    ),
    "pill": Style(
        name="Pill",
        # Larger than any control is tall, so every button and field reads as a
        # capsule. Qt clamps a radius to half the shorter side, which is what
        # makes one absurd number do the right thing at every control size.
        radius=999, radius_large=28, radius_small=999,
        spacing=18, padding=11,
    ),
    "compact": Style(
        name="Compact",
        radius=8, radius_large=12, radius_small=6,
        spacing=10, padding=6,
        font_size=13, heading_size=20,
        cover_size="small",
    ),
    "spacious": Style(
        name="Spacious",
        radius=14, radius_large=22, radius_small=10,
        spacing=28, padding=15,
        font_size=15, heading_size=28,
        cover_size="large",
    ),
    "flat": Style(
        name="Flat",
        radius=6, radius_large=10, radius_small=4,
        border_width=0,
        elevated_panels=False,
    ),
    "outlined": Style(
        name="Outlined",
        radius=10, radius_large=16, radius_small=7,
        border_width=2,
        elevated_panels=False,
    ),
    "big-text": Style(
        name="Big Text",
        radius=12, radius_large=18, radius_small=8,
        spacing=20, padding=12,
        font_size=17, heading_size=30,
        cover_size="large",
    ),
    "console": Style(
        name="Console",
        # Built for a television at three metres: everything larger, rounder
        # and further apart than a desk needs.
        radius=20, radius_large=30, radius_small=14,
        spacing=30, padding=16,
        font_size=18, heading_size=34,
        cover_size="huge",
    ),
}

DEFAULT_STYLE = "rounded"

# Kept as module constants because most of the interface reads them directly at
# construction time. They are the DEFAULT style's numbers; anything that honours
# a user's chosen style reads it from an `Appearance` instead.
_default_style = STYLES[DEFAULT_STYLE]
RADIUS_LARGE = _default_style.radius_large
RADIUS = _default_style.radius
RADIUS_SMALL = _default_style.radius_small
SPACING = _default_style.spacing


def set_active_style(style: "Style") -> None:
    """Point the module-level measurements at the user's chosen style.

    Dialogs and secondary screens build their own inline stylesheets from these
    at construction time, and there are enough of them that threading a style
    parameter through every one would be a lot of churn for a modest gain.
    Since each is constructed fresh when it opens — always after an appearance
    has been applied — reading the current numbers off the module gives them the
    right shape.

    The catch, and the reason this is a function rather than plain assignment:
    a module that did `from ... import RADIUS` binds the VALUE at import time
    and would never see an update. Callers that want to follow the style must
    reach it through the module, `ui_theme.RADIUS`.
    """
    global RADIUS, RADIUS_LARGE, RADIUS_SMALL, SPACING
    RADIUS = style.radius
    RADIUS_LARGE = style.radius_large
    RADIUS_SMALL = style.radius_small
    SPACING = style.spacing


@dataclass
class Appearance:
    """A theme and a style together — everything the interface looks like.

    The pair is what gets saved, restored and passed around. Either half can be
    swapped without touching the other, which is the whole point of the split.
    """

    theme: Theme = field(default_factory=lambda: THEMES[DEFAULT_THEME])
    style: Style = field(default_factory=lambda: STYLES[DEFAULT_STYLE])

    def to_dict(self) -> dict:
        return {"theme": self.theme.to_dict(), "style": self.style.to_dict()}

    @classmethod
    def from_dict(cls, data: dict) -> "Appearance":
        return cls(
            theme=Theme.from_dict(data.get("theme") or {}),
            style=Style.from_dict(data.get("style") or {}),
        )

    @classmethod
    def compose(
        cls,
        theme_name: str = DEFAULT_THEME,
        style_name: str = DEFAULT_STYLE,
        **overrides,
    ) -> "Appearance":
        """Build an appearance by name, with individual style axes overridden.

        This is what "mix and match" means in practice: any of the themes, any
        of the styles, and any single aspect — corner radius, density, font
        size, borders — changed on top of that without disturbing the rest.
        """
        return cls(
            theme=get_theme(theme_name),
            style=get_style(style_name).with_overrides(**overrides),
        )

    def stylesheet(self) -> str:
        return stylesheet(self.theme, self.style)


def get_theme(name: str) -> Theme:
    """Look up a built-in theme, falling back to the default."""
    return THEMES.get(name, THEMES[DEFAULT_THEME])


def get_style(name: str) -> Style:
    """Look up a built-in style, falling back to the default."""
    return STYLES.get(name, STYLES[DEFAULT_STYLE])


def list_theme_names() -> list[tuple[str, str]]:
    """(id, display name) for every built-in theme."""
    return [(key, theme.name) for key, theme in THEMES.items()]


def list_style_names() -> list[tuple[str, str]]:
    """(id, display name) for every built-in style."""
    return [(key, style.name) for key, style in STYLES.items()]


# ── Stylesheet ────────────────────────────────────────────────────

def stylesheet(theme: Theme, style: Optional[Style] = None) -> str:
    """The Qt stylesheet for a theme and a style.

    Every measurement comes from the style and every colour from the theme, so
    the two compose freely — this function is the only place that needs to know
    they were ever separate.

    Scrollbars are slim and unobtrusive; focus rings use the accent rather than
    the platform default so keyboard navigation stays visible in Big Picture.
    """
    style = style or STYLES[DEFAULT_STYLE]

    # A style with no borders still needs a colour for the places a border is
    # structural (the sidebar edge), so it collapses to the panel colour rather
    # than vanishing into an invisible 0px line.
    border = f"{style.border_width}px solid {theme.border}"
    # Panels either sit on their own surface or share the window's, which is
    # what makes the flat styles read as one continuous surface.
    panel_bg = theme.panel if style.elevated_panels else theme.background
    surface_bg = theme.surface if style.elevated_panels else theme.background

    RADIUS = style.radius
    RADIUS_LARGE = style.radius_large
    RADIUS_SMALL = style.radius_small

    return f"""
    QWidget {{
        background-color: {theme.background};
        color: {theme.text};
        font-size: {style.font_size}px;
    }}

    QMainWindow, QDialog {{
        background-color: {theme.background};
    }}

    /* ── Panels ─────────────────────────────────────────────── */

    #Sidebar {{
        background-color: {surface_bg};
        border-right: 1px solid {theme.border};
    }}

    #TopBar {{
        background-color: {surface_bg};
        border-bottom: 1px solid {theme.border};
    }}

    #DetailPanel {{
        background-color: {panel_bg};
        border-radius: {RADIUS_LARGE}px;
    }}

    /* ── Buttons ────────────────────────────────────────────── */

    QPushButton {{
        background-color: {panel_bg};
        color: {theme.text};
        border: {border};
        border-radius: {RADIUS}px;
        padding: {style.padding}px {style.padding * 2}px;
    }}

    QPushButton:hover {{
        background-color: {theme.elevated};
        border-color: {theme.accent_muted};
    }}

    QPushButton:pressed {{
        background-color: {theme.accent_muted};
    }}

    QPushButton:disabled {{
        color: {theme.text_dim};
        background-color: {surface_bg};
    }}

    QPushButton#Primary {{
        background-color: {theme.accent};
        color: {theme.background};
        border: none;
        font-weight: 600;
    }}

    QPushButton#Primary:hover {{
        background-color: {theme.text};
    }}

    /* Sidebar entries read as list rows, not buttons. */
    QPushButton#SidebarItem {{
        background-color: transparent;
        border: none;
        border-radius: {RADIUS}px;
        padding: 10px 14px;
        text-align: left;
    }}

    QPushButton#SidebarItem:hover {{
        background-color: {theme.panel};
    }}

    QPushButton#SidebarItem:checked {{
        background-color: {theme.accent_muted};
        color: {theme.text};
        font-weight: 600;
    }}

    QPushButton#SidebarToggle {{
        background-color: {theme.elevated};
        color: {theme.text};
        border: none;
        border-bottom: 1px solid {theme.border};
        border-radius: 0px;
        font-size: 18px;
        padding: 0px;
    }}

    QPushButton#SidebarToggle:hover {{
        background-color: {theme.accent};
        color: {theme.background};
    }}

    /* ── Inputs ─────────────────────────────────────────────── */

    QLineEdit {{
        background-color: {panel_bg};
        border: {border};
        border-radius: {RADIUS}px;
        padding: {style.padding}px {style.padding * 2}px;
        selection-background-color: {theme.accent_muted};
    }}

    QLineEdit:focus {{
        border-color: {theme.accent};
    }}

    QComboBox {{
        background-color: {panel_bg};
        border: {border};
        border-radius: {RADIUS}px;
        padding: {max(4, style.padding - 3)}px {style.padding + 2}px;
    }}

    QComboBox:hover {{
        border-color: {theme.accent_muted};
    }}

    QComboBox::drop-down {{
        border: none;
        width: 24px;
    }}

    QComboBox QAbstractItemView {{
        background-color: {theme.panel};
        border: 1px solid {theme.border};
        border-radius: {RADIUS_SMALL}px;
        selection-background-color: {theme.accent_muted};
        outline: none;
    }}

    QCheckBox::indicator {{
        width: {style.font_size + 4}px;
        height: {style.font_size + 4}px;
        border-radius: {RADIUS_SMALL}px;
        border: 1px solid {theme.border};
        background-color: {panel_bg};
    }}

    QCheckBox::indicator:checked {{
        background-color: {theme.accent};
        border-color: {theme.accent};
    }}

    /* ── Scrolling ──────────────────────────────────────────── */

    QScrollArea {{
        border: none;
        background-color: transparent;
    }}

    QScrollBar:vertical {{
        background: transparent;
        width: 10px;
        margin: 0;
    }}

    QScrollBar::handle:vertical {{
        background: {theme.elevated};
        border-radius: 5px;
        min-height: 40px;
    }}

    QScrollBar::handle:vertical:hover {{
        background: {theme.accent_muted};
    }}

    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {{
        height: 0;
        background: none;
    }}

    QScrollBar:horizontal {{
        background: transparent;
        height: 10px;
    }}

    QScrollBar::handle:horizontal {{
        background: {theme.elevated};
        border-radius: 5px;
        min-width: 40px;
    }}

    QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,
    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{
        width: 0;
        background: none;
    }}

    /* ── Misc ───────────────────────────────────────────────── */

    QLabel#Heading {{
        font-size: {style.heading_size}px;
        font-weight: 700;
    }}

    QLabel#Subtle {{
        color: {theme.text_dim};
    }}

    QToolTip {{
        background-color: {theme.elevated};
        color: {theme.text};
        border: 1px solid {theme.border};
        border-radius: {RADIUS_SMALL}px;
        padding: 6px 10px;
    }}

    QMenu {{
        background-color: {theme.panel};
        border: 1px solid {theme.border};
        border-radius: {RADIUS}px;
        padding: 6px;
    }}

    QMenu::item {{
        padding: 7px 22px;
        border-radius: {RADIUS_SMALL}px;
    }}

    QMenu::item:selected {{
        background-color: {theme.accent_muted};
    }}

    QProgressBar {{
        background-color: {panel_bg};
        border: none;
        border-radius: 4px;
        height: 8px;
        text-align: center;
    }}

    QProgressBar::chunk {{
        background-color: {theme.accent};
        border-radius: 4px;
    }}
    """
